### PR TITLE
Remove dynamically linked libSwiftPMDataModel

### PR DESCRIPTION
**Pull request by yonihemi**

### CODE REVIEW

**Review by MaxDesiatov — APPROVED** [review]

**Comment by MaxDesiatov** [comment]
We might still need to specify URLs to bottles manually, the bottle update script seems to be somewhat broken

**Comment by MaxDesiatov** [comment]
What I usually do to build bottles locally is this:

```
brew uninstall carton && brew install --build-bottle --verbose swiftwasm/tap/carton
```

Then I run `brew bottle swiftwasm/tap/carton`. I think either of these commands produces a Ruby snippet for the formula, you can also look up previous commits for examples. You'll have to rename the produced tarball to remove `.1` suffix, and upload that to the tagged release in `carton` repo.

Or don't bother with this if you don't have time, the only downside is that `carton` will be rebuilt on user's machine instead of installing binaries from bottles.

**Comment by MaxDesiatov** [comment]
I've uploaded the bottles for both arm64 and x86_64, the formula is updated as well.

**Comment by yonihemi** [comment]
Thanks. I didn't manage building locally.

**Pull request merged**
